### ISSUE TITLE
vertical offset calculations

### ISSUE THREAD

**Issue by pro2on** [rylexr/android-show-hide-toolbar#1]
May be its useful to calculate
verticalOffset = rvCities.computeVerticalScrollOffset();

instead of
verticalOffset += dy;

**Comment by rylexr** [comment]
Current Support Library version has RecyclerView.computeVerticalScrollOffset() with protected visibility. Fortunately, Google pull the right move in making it public in latest version of library. I just updated the code to make it work with version 22.2.+ and as a bonus I made a **new utility class** [RecyclerViewUtils.ShowHideToolbarOnScrollingListener](https://github.com/rylexr/android-show-hide-toolbar/blob/master/app/src/main/java/com/tinbytes/samples/showhidetoolbar/util/RecyclerViewUtils.java) to simplify hide/show of Toolbar. Check the code in [MainActivity2.java](https://github.com/rylexr/android-show-hide-toolbar/blob/master/app/src/main/java/com/tinbytes/samples/showhidetoolbar/MainActivity2.java) to see how to use it (much more cleaner).

Thanks for the suggestion.
