### ISSUE TITLE
Can we make it work with ScrollView or ListView also

### ISSUE THREAD

**Issue by amrut8winjit** [rylexr/android-show-hide-toolbar#2]
I want to use this feature with scroll view. is it possible with this library/sample?

**Comment by rylexr** [comment]
Check this class here https://github.com/rylexr/android-show-hide-toolbar/blob/master/app/src/main/java/com/tinbytes/samples/showhidetoolbar/util/RecyclerViewUtils.java. It should be pretty straightforward to implement something similar for ScrollView/ListView. All you need is to register a way to detect scrolling changes. Maybe something like:

``` java
scrollView.getViewTreeObserver().addOnScrollChangedListener(new OnScrollChangedListener() {
    @Override
    public void onScrollChanged() {
        int scrollX = scrollView.getScrollX();
        int scrollY = scrollView.getScrollY();
        // Do the rest here

    }
});
```

Hope this helps.

Edit: Typo

**Comment by amrut8winjit** [comment]
what is `rootScrollView` in the code u suggested here?

**Comment by rylexr** [comment]
Sorry. There was a typo. I've fixed the code.

**Comment by amrut8winjit** [comment]
Thank You. I have found some other solution. https://github.com/JohannBlake/JBHeaderScroll
